app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from members.views import signup_view
from posts.views import post_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', signup_view, name='signup'),
    path('members/', include('members.urls')),
    path('posts/', include('posts.urls')),

    path('explore/tags/<str:tag>/', post_list, name='post-list-by-tag'),
]
urlpatterns += static(
    # URL앞부분이 /media/이면
    prefix=settings.MEDIA_URL,
    # document_root위치에서 나머지 path에 해당하는 파일을 리턴
    document_root=settings.MEDIA_ROOT,
)

app/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    # /posts/
    # views.post_list(request)
    path('', views.post_list, name='post-list'),

    # /posts/5/like/
    # views.post_like(request, pk=5)
    path('<int:pk>/like/', views.post_like, name='post-like'),

    # /posts/create/
    path('create/', views.post_create, name='post-create'),

    # /posts/3/comments/create/
    # views.post_create(request, post_pk=3)
    path('<int:post_pk>/comments/create/', views.comment_create, name='comment-create'),
]

app/posts/models.py
import re

from django.db import models

from members.models import User


class Post(models.Model):
    TAG_PATTERN = re.compile(r'#(\w+)')
    """
    인스타그램의 포스트
    """
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    content_html = models.TextField(blank=True)
    like_users = models.ManyToManyField(
        User, through='PostLike', related_name='like_post_set',
    )
    tags = models.ManyToManyField(
        'Tag', verbose_name='해시태그 목록', related_name='posts', blank=True,
    )
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return '{author} | {created}'.format(
            author=self.author.username,
            created=self.created,
        )

    def _save_html(self):
        """
        content속성의 값을 사용해서 해시태그에 해당하는 문자열을 a태그로 바꾸어 줌
        :return: 해시태그가 a태그로 변환된 HTML
        """
        self.content_html = re.sub(
            self.TAG_PATTERN,
            r'<a href="/explore/tags/\g<1>/">#\g<1></a>',
            self.content,
        )

    def _save_tags(self):
        """
        content에 포함된 해시태그 문자열 (ex: #Python)의 Tag들을 만들고,
        자신의 tags Many-to-many field에 추가한다
        """
        tag_name_list = re.findall(self.TAG_PATTERN, self.content)
        tags = [Tag.objects.get_or_create(name=tag_name)[0] for tag_name in tag_name_list]
        self.tags.set(tags)

    def save(self, *args, **kwargs):
        self._save_html()
        super().save(*args, **kwargs)
        self._save_tags()


class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='posts/images')


class PostComment(models.Model):
    # postcomment_set <- related_name
    #  반대쪽 객체에서 사용
    #   post.postcomment_set
    #
    # postcomment     <- related_query_name
    #  반대쪽 QuerySet의 filter조건 키워드명으로 사용
    #   Post.objects.filter(postcomment__)
    #
    # 기본값
    #  related_name:        <모델클래스명의 lowercase>_set
    #  related_query_name:  <모델클래스명의 lowercase>
    #
    # related_name을 지정하고, related_query_name은 지정하지 않은 경우
    #  related_name:        지정한 related_name
    #  related_query_name:  지정한 related_name
    #   ex) Post와 Tag관계(M2M)에서, tags필드에서의 related_name이 posts인 경우
    #       tag.posts.all()                 <- related_name
    #       Tag.objects.filter(posts__)      <- related_query_name

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()

    class Meta:
        ordering = ('-pk',)


class PostLike(models.Model):
    """
    사용자가 좋아요 누른 Post정보를 저장
    Many-to-many필드를 중간모델(Intermediate Model)을 거쳐 사용
     언제 생성되었는지를 Extra field로 저장! (created)
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    """
    Many-to-many에서, 필드는 Post에 클래스에 작성
    HashTag의 Tag를 담당
    Post입장에서 post.tags.all()로 연결된 전체 Tag를 불러올 수 있어야 함
    Tag 입장에서 tag.posts.all()로 연결된 전체 Post를 불러올 수 있어야 함

    Django admin에서 결과를 볼 수 있도록 admin.py에 적절히 내용 기록

    중개모델(Intermediate model)을 사용할 필요 없음
    """
    name = models.CharField('태그명', max_length=100)

    def __str__(self):
        return self.name

app/posts/forms.py
from django import forms


class PostCreateForm(forms.Form):
    """
    이 Form에 들어갈 입력요소
        Image(File)
        Text
    """
    image = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control-file',
                'multiple': True,
            }
        )
    )
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
            }
        )
    )

    def save(self):
        pass


class CommentCreateForm(forms.Form):
    content = forms.CharField(
        max_length=10,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': 2,
            }
        )
    )

    def save(self, post, author):
        return post.postcomment_set.create(
            author=author,
            content=self.cleaned_data['content'],
        )

app/posts/views.py
from django.shortcuts import render, redirect
from .models import Post, PostLike, PostImage
from .forms import PostCreateForm, CommentCreateForm


def post_list(request, tag=None):
    # 1. 로그인 완료 후 이 페이지로 이동하도록 함
    # 2. index에 접근할 때 로그인이 되어 있다면, 이 페이지로 이동하도록 함
    #    로그인이 되어있는지 확인:
    #       request.user.is_authenticated가 True인지 체크
    #
    # URL:      /posts/  (posts.urls를 사용, config.urls에서 include)
    #           app_name: 'posts'
    #           url name: 'post-list'
    #           -> posts:post-list
    # Template: templates/posts/post-list.html
    #           <h1>Post List</h1>

    # 'posts'라는 키로 모든 Post QuerySet을 전달
    #  (순서는 pk의 역순)
    # 그리고 전달받은 QuerySet을 순회하며 적절히 Post내용을 출력
    if tag is None:
        posts = Post.objects.order_by('-pk')
    else:
        posts = Post.objects.filter(tags__name__iexact=tag).order_by('-pk')

    comment_form = CommentCreateForm()
    context = {
        'posts': posts,
        'comment_form': comment_form,
    }
    return render(request, 'posts/post-list.html', context)


def post_like(request, pk):
    """
    pk가 pk인 Post와 (변수명 post사용)
    request.user로 전달되는 User (변수명 user사용)에 대해

    1. PostLike(post=post, user=user)인 PostLike객체가 존재하는지 확인한다
    2-1. 만약 해당 객체가 이미 있다면, 삭제한다
    2-2. 만약 해당 객체가 없다면 새로 만든다
    3. 완료 후 posts:post-list로 redirect한다

    URL: /posts/<pk>/like/
    """
    post = Post.objects.get(pk=pk)
    user = request.user
    print('post:', post)
    print('user:', user)

    post_like_qs = PostLike.objects.filter(post=post, user=user)
    # user, post에 해당하는 PostLike가 있는 경우
    if post_like_qs.exists():
        # 삭제
        post_like_qs.delete()
    # 없는 경우
    else:
        # 만든다
        PostLike.objects.create(post=post, user=user)

    return redirect('posts:post-list')


def post_create(request):
    """
    URL:        /posts/create/, name='post-create'
    Template:   /posts/post-create.html
    forms.PostCreateForm을 사용
    """
    if request.method == 'POST':
        # 새 Post를 생성
        # user는 request.user
        # 전달받는 데이터: image, text
        #  image는 request.FILES에 있음
        #  text는  request.POST에 있음

        # Post를 생성 (변수명 post를 사용)
        #   request.user와 text를 사용
        # PostImage를 생성
        #   post와 전달받은 image를 사용
        # 모든 생성이 완료되면 posts:post-list로 redirect
        text = request.POST['text']
        images = request.FILES.getlist('image')

        post = Post.objects.create(
            author=request.user,
            content=text
        )
        for image in images:
            post.postimage_set.create(image=image)

        return redirect('posts:post-list')
    else:
        form = PostCreateForm()
        context = {
            'form': form,
        }
        return render(request, 'posts/post-create.html', context)


def comment_create(request, post_pk):
    # URL: /posts/<int:post_pk>/comments/create/
    # Template: 없음 (post-list.html내에 Form을 구현)
    #  post-list.html 내부에서, 각 Post마다 자신에게 연결된 PostComment목록을 보여주도록 함
    #   보여주는형식은
    #    <ul>
    #     <li><b>작성자명</b> <span>내용</span></li>
    #     <li><b>작성자명</b> <span>내용</span></li>
    #    </ul>
    if request.method == 'POST':
        post = Post.objects.get(pk=post_pk)
        # Form인스턴스를 만드는데, data에 request.POST로 전달된 dict를 입력
        form = CommentCreateForm(data=request.POST)
        # Form인스턴스 생성시, 주어진 데이터가
        # 해당 Form이 가진 Field들에 적절한 데이터인지 검증
        if form.is_valid():
            form.save(post=post, author=request.user)
        return redirect('posts:post-list')

app/templates/posts/post-create.html
{% extends 'base.html' %}

{% block content %}
    <div class="container pt-4">
        <h1>새 포스트 작성</h1>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary btn-block">작성</button>
        </form>
    </div>
{% endblock %}

app/templates/posts/post-list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container pt-2">
        <div class="row">
            {% for post in posts %}
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="card mb-2">
                        <div class="card-header">
                            <span>PK: {{ post.pk }}</span>
                            <span class="float-right">{{ post.author.username }} ({{ post.author.pk }})</span>
                        </div>
                        <div>
                            {% for post_image in post.postimage_set.all %}
                                <img src="{{ post_image.image.url }}" alt="" style="width: 100%;">
                            {% endfor %}
                        </div>
                        <div class="card-body">
                            <div class="btn-container">
                                <div class="d-inline-block">
                                    <form action="{% url 'posts:post-like' pk=post.pk %}" method="POST" class="d-inline-block">
                                        {% csrf_token %}
                                        {% if post in user.like_post_set.all %}
                                            <button class="btn btn-sm btn-primary" type="submit">Liked
                                                ({{ post.like_users.count }})
                                            </button>
                                        {% else %}
                                            <button class="btn btn-sm btn-outline-primary" type="submit">Like
                                                ({{ post.like_users.count }})
                                            </button>
                                        {% endif %}
                                    </form>
                                    <button class="btn btn-sm btn-success">Comments ({{ post.postcomment_set.count }})</button>
                                </div>
                                <small class="float-right">{{ post.created }}</small>
                            </div>
                            <div class="content-container">
                                {{ post.content_html|safe }}
                            </div>
                            <div class="comments-container">
                                <ul class="list-unstyled">
                                    {% for comment in post.postcomment_set.all %}
                                        <li>
                                            <b>{{ comment.author.name }} ({{ comment.author.pk }})</b>
                                            <span>{{ comment.content }} ({{ comment.pk }})</span>
                                        </li>
                                    {% endfor %}
                                </ul>
                                <div>
                                    <!-- Comment를 작성하는 Form -->
                                    <form action="{% url 'posts:comment-create' post_pk=post.pk %}" method="POST">
                                        {% csrf_token %}
                                        {% for field in comment_form %}
                                            {{ field }}
                                        {% endfor %}
                                        <button type="submit" class="btn btn-primary btn-sm btn-block mt-1">작성</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}