app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from members.views import signup_view
from posts.views import post_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', signup_view, name='signup'),
    path('members/', include('members.urls')),
    path('posts/', include('posts.urls')),

    path('explore/tags/<str:tag>/', post_list, name='post-list-by-tag'),
]
urlpatterns += static(
    # URL앞부분이 /media/이면
    prefix=settings.MEDIA_URL,
    # document_root위치에서 나머지 path에 해당하는 파일을 리턴
    document_root=settings.MEDIA_ROOT,
)

app/members/urls.py
from django.urls import path

from . import views

app_name = 'members'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('naver-login/', views.naver_login, name='naver-login'),
]

app/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    # /posts/
    # views.post_list(request)
    path('', views.post_list, name='post-list'),

    # /posts/5/like/
    # views.post_like(request, pk=5)
    path('<int:pk>/like/', views.post_like, name='post-like'),

    # /posts/create/
    path('create/', views.post_create, name='post-create'),

    # /posts/3/comments/create/
    # views.post_create(request, post_pk=3)
    path('<int:post_pk>/comments/create/', views.comment_create, name='comment-create'),
]

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}">
    <title>Instagram</title>
    {% block head %}{% endblock %}
    <style>
        html {
            font-size: .9rem;
        }
    </style>
</head>
<body>
    <div id="wrap">
        <nav class="navbar navbar-expand navbar-dark bg-dark">
            <a href="{% url 'signup' %}" class="navbar-brand">Instagram</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="#" class="nav-link">{{ user.username }}</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'members:logout' %}" class="nav-link">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a href="{% url 'members:login' %}" class="nav-link">Login</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a href="{% url 'posts:post-create' %}" class="nav-link text-white btn btn-primary btn-sm">+ Add Post</a>
                    </li>
                </ul>
            </div>
        </nav>

        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="mr-auto ml-auto mt-3
                    col-lg-4
                    col-md-6
                    col-sm-8
                    col-10">
            <div class="card text-center p-4">
                <div>{{ request.user }}</div>
                <div>{{ request.user.is_authenticated }}</div>

                <h1>Instagram</h1>
                <p class="text-secondary">친구들의 사진과 동영상을 보려면 가입하세요</p>
                <button class="btn btn-primary btn-block">Facebook으로 로그인</button>
                <hr>
                <form action="{% url 'members:signup' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <input name="email" type="email" class="form-control" placeholder="이메일 주소">
                    </div>
                    <div class="form-group">
                        <input name="name" type="text" class="form-control" placeholder="성명">
                    </div>
                    <div class="form-group">
                        <input name="username" type="text" class="form-control" placeholder="사용자 이름">
                    </div>
                    <div class="form-group">
                        <input name="password" type="password" class="form-control" placeholder="비밀번호">
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">가입</button>
                </form>
                <p class="text-secondary">가입하면 Instagram의 약관 데이터 정책 및 쿠키 정책에 동의하게 됩니다</p>
            </div>

            <div class="card text-center p-4 mt-3 mb-3">
                <span>계정이 있으신가요?</span>
                <a href="{% url 'members:login' %}">로그인</a>
            </div>
        </div>
    </div>
{% endblock %}